tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: docker-compose
    command: |
      gp open GITPOD.md
      bash /workspace/fusionauth-example-express-start-here/ports.sh
      docker compose up
      gp preview `gp url 9011`

ports:
  - port: 9011
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
  - port: 9020
    onOpen: ignore
    visibility: public
  - port: 9021
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
