tasks:

  # ------------------------------------
  # Start FusionAuth in Docker
  # ------------------------------------
  - name: docker-compose
    before: |
      bash /workspace/fusionauth-example-express-start-here/ports.sh
    command: |
      echo "Enter 'docker compose -up' to start the servers"

ports:
  - port: 9011
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 9012
    onOpen: ignore
    visibility: public
  - port: 9020
    onOpen: ignore
    visibility: public
  - port: 9021
    onOpen: ignore
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: public
